spring.application.name=xs-bbs
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.messages.encoding=UTF-8

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xsbbs?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.cache.type=simple

mybatis-plus.configuration.map-underscore-to-camel-case=true

app.match.thought-threshold=0.42
app.match.reveal-threshold=60
app.outbox.batch-size=20
app.outbox.fixed-delay-ms=2000
app.outbox.topic=xs-bbs.outbox
app.outbox.consumer-group=xs-bbs-outbox-consumer-local
app.outbox.max-retry-count=5
app.outbox.retry-base-delay-ms=5000
app.outbox.retry-max-delay-ms=60000
app.outbox.publish-timeout-ms=30000
app.outbox.dead-letter-topic=xs-bbs.outbox.dlq
app.notification.topic=xs-bbs.notification
app.notification.consumer-group=xs-bbs-notification-consumer-local
app.web.allowed-origins=http://127.0.0.1:5173,http://localhost:5173
app.web.allowed-origin-patterns=http://127.0.0.1:*,http://localhost:*,http://192.168.*.*:*,http://10.*.*.*:*,http://172.*.*.*:*
app.ai.mode=compatible
app.ai.provider-name=zhipu
app.ai.prompt-version=v2
app.ai.request-timeout-ms=10000
app.ai.max-tags=5
app.ai.chat-base-url=https://open.bigmodel.cn/api/paas/v4
app.ai.chat-path=/chat/completions
app.ai.chat-api-key=927fe5a312734a3faf822ecc03241f5c.IArdjb2PExH6JLYu
app.ai.chat-model=glm-4.7
app.ai.embedding-base-url=https://open.bigmodel.cn/api/paas/v4
app.ai.embedding-path=/embeddings
app.ai.embedding-api-key=927fe5a312734a3faf822ecc03241f5c.IArdjb2PExH6JLYu
app.ai.embedding-model=embedding-3

sa-token.token-name=xs-bbs-token
sa-token.timeout=604800
sa-token.active-timeout=1800
sa-token.is-concurrent=true
sa-token.is-share=false
sa-token.token-style=random-64
