spring.cache.type=redis
spring.data.redis.host=${XS_BBS_REDIS_HOST:127.0.0.1}
spring.data.redis.port=${XS_BBS_REDIS_PORT:6379}
spring.data.redis.password=${XS_BBS_REDIS_PASSWORD:}
spring.data.redis.database=${XS_BBS_REDIS_DATABASE:0}
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=xs-bbs:
