spring.datasource.url=jdbc:mysql://${XS_BBS_DB_HOST:mysql}:${XS_BBS_DB_PORT:3306}/${XS_BBS_DB_NAME:xsbbs}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.data.redis.host=${XS_BBS_REDIS_HOST:redis}
rocketmq.name-server=${XS_BBS_RMQ_NAME_SERVER:rocketmq-namesrv:9876}
